# Atomic Coordinate Parsing (atom_parse_coords.py)
geometry_file_names: geometry
geometry_folder: atom_geometries
descriptor_file_names: desc
descriptor_folder: desc_out
output_read_folder: orca_outputs
run_id: 1

# Descriptor Values/Hyperparameters
epsilon: 1e-12 # needs to be very small
eta: 1.0 # ~ E-1 – E+1,  higher value = narrower peak
zeta: 2.0 # usually a small, positive integer, higher value = higher angular resolution
r_s: 0.0 # small
r_cut: 5.0 # ~ E0, Angstroms
lambda_: 1.0 # typically ±1